<a href="https://colab.research.google.com/github/AadityaAdh/tf_useful_functions/blob/main/tf_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

#Common tensorflow functions

#To increase dimension: tf.expand_dims

Returns a tensor with a length 1 axis inserted at index axis.


dimension baduna kunai element halni haina ki
bracket thapni vaya ho
kaa thapni vanae ra chai axis lae vanxa

tf.expand_dims(

  
    input, axis, name=None
)


In [ ]:
image = tf.zeros([2,2,3])
image

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.expand_dims(image, axis=0).shape


TensorShape([1, 10, 10, 3])

In [ ]:
tf.expand_dims(image, axis=1)
#shape ko index 1 ma 1 aako jasto ho

<tf.Tensor: shape=(2, 1, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
tf.expand_dims(image, axis=2)

<tf.Tensor: shape=(2, 2, 1, 3), dtype=float32, numpy=
array([[[[0., 0., 0.]],

        [[0., 0., 0.]]],


       [[[0., 0., 0.]],

        [[0., 0., 0.]]]], dtype=float32)>

In [ ]:
tf.reshape(image,(2,2,1,3))

<tf.Tensor: shape=(2, 2, 1, 3), dtype=float32, numpy=
array([[[[0., 0., 0.]],

        [[0., 0., 0.]]],


       [[[0., 0., 0.]],

        [[0., 0., 0.]]]], dtype=float32)>

#reshape garnu ra expanding dims garnu yeutai ho
yedi final output ko shape milni tha xa vanae rehspe use garni

natra expand_dims garni

#Squeeze tf.squeeze
#shape ma jaa jaa 1 xa tyo sabbai hatxa

Removes dimensions of size 1 from the shape of a tensor.

tf.squeeze(


    input, axis=None, name=None
)


1 shape ko khasai significance hudaina so squeeze gardini ie:

[[m1]]
lekhnu satta [m1] lekhnu ramro ra indexing garna sajilo hunxa



In [ ]:
x=tf.constant([1,2,3,4,5,6],shape=[1,1,1,6])
x

<tf.Tensor: shape=(1, 1, 1, 6), dtype=int32, numpy=array([[[[1, 2, 3, 4, 5, 6]]]], dtype=int32)>

In [ ]:
#aaba (1, 1, 1, 6) ma squeeze garda baki hunxa 6 matra as jaa jaa 1 xa tyo sabbai hatxa
tf.squeeze(x)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
x=tf.constant([1,2,3,4,5,6],shape=[1,1,1,6])
x

<tf.Tensor: shape=(1, 1, 1, 6), dtype=int32, numpy=array([[[[1, 2, 3, 4, 5, 6]]]], dtype=int32)>

In [ ]:
#tara yedi kunai kunai matrai 1 hataunu xa vanae tyo axis specify garnu parxa ie
#shape=(1, 1, 1, 6) yedi 2nd ra 3rd ko 1  hataunu xa vanae tesko axis vanae ko 1 ra 2 ho
#so specify it in axis
tf.squeeze(x,[1,2]).shape

TensorShape([1, 6])

#Reshape tf.reshape


Reshapes a tensor.

tf.reshape(


    tensor, shape, name=None
)



In [ ]:
t1 = [[1, 2, 3],
      [4, 5, 6]]
print(tf.shape(t1).numpy())







[2 3]


In [ ]:
t2 = tf.reshape(t1, [6])
t2


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
tf.reshape(t2, [3, 2])

#Concatinating tf.concat



Concatenates tensors along one dimension.

tf.concat(


    values, axis, name='concat'
)




In [ ]:
#column concatinate vayo
#or 1st 1st  matrix jodiyo
#colum wise
#2nd 2nd ma ni same
t1 = [[[1, 2], [2, 3]], [[4, 4], [5, 3]]]
t2 = [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]
tf.concat([t1, t2], 2)


<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  7,  4],
        [ 2,  3,  8,  4]],

       [[ 4,  4,  2, 10],
        [ 5,  3, 15, 11]]], dtype=int32)>

In [ ]:
tf.concat([t1, t2], 1)
#row wise basyo

<tf.Tensor: shape=(2, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 2,  3],
        [ 7,  4],
        [ 8,  4]],

       [[ 4,  4],
        [ 5,  3],
        [ 2, 10],
        [15, 11]]], dtype=int32)>

In [ ]:
tf.concat([t1, t2], 0)
#dimesnion ni badyo
#as naya array banyo duita matrix store garna

<tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 2,  3]],

       [[ 4,  4],
        [ 5,  3]],

       [[ 7,  4],
        [ 8,  4]],

       [[ 2, 10],
        [15, 11]]], dtype=int32)>

#Stacking tf.stack
#tf.stack introduces a new axis and increases the rank of the tensors.
#tf.concat concatenates along an existing axis and maintains the rank of the tensors.

concatinating joins tensors along an existing axis
stacking joins tensors along a new axis


In [4]:


# Creating three 3-dimensional tensors
tensor1 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                      [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

tensor2 = tf.constant([[[28, 29, 30], [31, 32, 33], [34, 35, 36]],
                      [[37, 38, 39], [40, 41, 42], [43, 44, 45]],
                      [[46, 47, 48], [49, 50, 51], [52, 53, 54]]])
tensor1


<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

In [ ]:
# Stacking along axis=0
stacked_tensor_axis_0 = tf.stack([tensor1, tensor2], axis=0)
stacked_tensor_axis_0

<tf.Tensor: shape=(2, 3, 3, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]],


       [[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]]], dtype=int32)>

In [ ]:
# Stacking along axis=1
stacked_tensor_axis_1 = tf.stack([tensor1, tensor2], axis=1)
stacked_tensor_axis_1




<tf.Tensor: shape=(3, 2, 3, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]]],


       [[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]]],


       [[[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]]], dtype=int32)>

In [ ]:

# Stacking along axis=2
stacked_tensor_axis_2 = tf.stack([tensor1, tensor2], axis=2)
stacked_tensor_axis_2

<tf.Tensor: shape=(3, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [28, 29, 30]],

        [[ 4,  5,  6],
         [31, 32, 33]],

        [[ 7,  8,  9],
         [34, 35, 36]]],


       [[[10, 11, 12],
         [37, 38, 39]],

        [[13, 14, 15],
         [40, 41, 42]],

        [[16, 17, 18],
         [43, 44, 45]]],


       [[[19, 20, 21],
         [46, 47, 48]],

        [[22, 23, 24],
         [49, 50, 51]],

        [[25, 26, 27],
         [52, 53, 54]]]], dtype=int32)>

In [13]:
#in 3d
import numpy as np
t1_in3d=tf.constant(np.arange(1,28),shape=[3,3,3])
t1_in3d

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [7]:
t2_in3d=tf.constant(np.arange(28,55),shape=[3,3,3])
t2_in3d

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])>

In [11]:
t3_in3d=tf.constant(np.arange(55,82),shape=[3,3,3])
t3_in3d

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[55, 56, 57],
        [58, 59, 60],
        [61, 62, 63]],

       [[64, 65, 66],
        [67, 68, 69],
        [70, 71, 72]],

       [[73, 74, 75],
        [76, 77, 78],
        [79, 80, 81]]])>

#concat vs stack
concat yedi row ra column axis ma garya xa vanae matrix lai kholae ra garxa


stack ko concept aarkai
yeuta matrix lai aarko ko top ma rakhnu ho
yedi existing shape(3,3,3)
xa aani axis 0 ma stack garya xa vanae
shape ko 0th index ma aarko value thapni ho
yedi vitra 2 ta tensors xa vanae
staack ko result ko shape(2,3,3,3) hunxa
yedi axis 1 result shape(3,2,3,3) hunxa

so usage:
yedi duita matrix lai jode ra yeuta banaunu xa vanae concat use garam
tara haina malai sangai sangai matra rakhxu tara na jodi vanae stack garam

#concat vs stack
Axis 0

In [17]:
contensor=tf.concat([t1_in3d,t2_in3d,t3_in3d],0)
#vanya  sangsangai rakhni vanya
#sabbai lai sang sangai rakhni matrai vanya ho
contensor





<tf.Tensor: shape=(9, 3, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]],

       [[55, 56, 57],
        [58, 59, 60],
        [61, 62, 63]],

       [[64, 65, 66],
        [67, 68, 69],
        [70, 71, 72]],

       [[73, 74, 75],
        [76, 77, 78],
        [79, 80, 81]]])>

In [18]:
stacktensor=tf.stack([t1_in3d,t2_in3d,t3_in3d],0)
#vanya  sangsangai rakhni vanya
#sabbai lai sang sangai rakhni matrai vanya ho
stacktensor

<tf.Tensor: shape=(3, 3, 3, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]],


       [[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]]]])>

so concat lae 3 ootai tensors ma vako value lai yeutai matrix ma haldyo
#so concat vanya jodni ho

tara stack lae yeutai banayo banauna ta tara 3 oota tensors lai farak farak matix ma haldyo yeutai vitra tara

#so stack vanya yeuta mathi aarko rakhni ho

#yesai bhujam
jun axis dya ho tesko starting ra ending bracket samatxa sabbai ko aani

concat lae chai ta vitra vako element lai yeutai ma lekhxa

stack lae chai tya vitra ko element lai yeuta mathi aarko


like yedi dita xan tensors
[m1,m3]=t1,[m2,m4]=t2


aaba concat garda on axis 0

[1st element inside that bracket=m1(tyo vanda paxadi ko bracket nai m1 ho),


1st element inside that bracket for another=m2
.
.
.
so m1+m2 garya vanam yeuta vitra
],


[
  2nd element inside that bracket=m3,

  
2nd element inside that bracket for another=m4
]



aani stack garda [m1,m3]=t1,[m2,m4]=t2


[[1st element inside that bracket=m1],


[1st element inside that bracket for another=m2]
.
.
.
simply top top ma rakhya
],


[
  [2nd element inside that bracket=m3],


[2nd element inside that bracket for another=m4]
]

In [19]:
#concat in axis=1
contensor=tf.concat([t1_in3d,t2_in3d,t3_in3d],1)
#vanya  sangsangai rakhni vanya
#sabbai lai sang sangai rakhni matrai vanya ho
contensor

<tf.Tensor: shape=(3, 9, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [55, 56, 57],
        [58, 59, 60],
        [61, 62, 63]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [37, 38, 39],
        [40, 41, 42],
        [43, 44, 45],
        [64, 65, 66],
        [67, 68, 69],
        [70, 71, 72]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54],
        [73, 74, 75],
        [76, 77, 78],
        [79, 80, 81]]])>

In [20]:
stacktensor=tf.stack([t1_in3d,t2_in3d,t3_in3d],1)
#vanya  sangsangai rakhni vanya
#sabbai lai sang sangai rakhni matrai vanya ho
stacktensor

<tf.Tensor: shape=(3, 3, 3, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]]],


       [[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]],


       [[[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]]]])>

In [21]:
stacktensor=tf.stack([t1_in3d,t2_in3d,t3_in3d],2)
#vanya  sangsangai rakhni vanya
#sabbai lai sang sangai rakhni matrai vanya ho
stacktensor

<tf.Tensor: shape=(3, 3, 3, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [28, 29, 30],
         [55, 56, 57]],

        [[ 4,  5,  6],
         [31, 32, 33],
         [58, 59, 60]],

        [[ 7,  8,  9],
         [34, 35, 36],
         [61, 62, 63]]],


       [[[10, 11, 12],
         [37, 38, 39],
         [64, 65, 66]],

        [[13, 14, 15],
         [40, 41, 42],
         [67, 68, 69]],

        [[16, 17, 18],
         [43, 44, 45],
         [70, 71, 72]]],


       [[[19, 20, 21],
         [46, 47, 48],
         [73, 74, 75]],

        [[22, 23, 24],
         [49, 50, 51],
         [76, 77, 78]],

        [[25, 26, 27],
         [52, 53, 54],
         [79, 80, 81]]]])>

In [22]:
stacktensor=tf.concat([t1_in3d,t2_in3d,t3_in3d],2)
#vanya  sangsangai rakhni vanya
#sabbai lai sang sangai rakhni matrai vanya ho
stacktensor

<tf.Tensor: shape=(3, 3, 9), dtype=int64, numpy=
array([[[ 1,  2,  3, 28, 29, 30, 55, 56, 57],
        [ 4,  5,  6, 31, 32, 33, 58, 59, 60],
        [ 7,  8,  9, 34, 35, 36, 61, 62, 63]],

       [[10, 11, 12, 37, 38, 39, 64, 65, 66],
        [13, 14, 15, 40, 41, 42, 67, 68, 69],
        [16, 17, 18, 43, 44, 45, 70, 71, 72]],

       [[19, 20, 21, 46, 47, 48, 73, 74, 75],
        [22, 23, 24, 49, 50, 51, 76, 77, 78],
        [25, 26, 27, 52, 53, 54, 79, 80, 81]]])>

#yesari bhujni wala sajilo  xa
tyo bracket samauni aani tesko vitra ko bracket yeuta element hunxa concat ma vayae element wise concat gardai jani
stackk ma vayae mathi rakhdai jani

#Padding. tf.pad



Pads a tensor.

tf.pad(


    tensor, paddings, mode='CONSTANT', constant_values=0, name=None
)


tensor  vanya matrix haru vai halae
paddings vanya pani tensor nai hun ie
[[1,1],[2,2]]

first1 =kati oota row halni mathi pati padding ko


2nd 1=muni kati oota row halni padding ko

1st 2=kati oota column halni left side ma


2nd 2=kati oota column halni right side ma

with that constant value



In [23]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
tf.pad(t, paddings, "CONSTANT")  # [[0, 0, 0, 0, 0, 0, 0],
                                 #  [0, 0, 1, 2, 3, 0, 0],
                                 #  [0, 0, 4, 5, 6, 0, 0],
                                 #  [0, 0, 0, 0, 0, 0, 0]]



<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [24]:
#so 1 oota row muni ra mathi
#2 oota column left ra right


In [25]:
#lets do this for 3d
t1_in3d

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [30]:
tf.pad(t1_in3d,[[1,1],[2,2],[0,0]],"CONSTANT")

<tf.Tensor: shape=(5, 7, 3), dtype=int64, numpy=
array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])>

#padding ma dini tensor axis aanusar huni raixa
for 3d tensors 3 oota row hunu paryo
[[1,1],[2,2],[3,3]]

first 1=kati oota channel mathi thapni

secound1=kati oota channel muni thaapni

first 2 =kati oota row mathi thapni
......